import { Sidebar } from "@/components/layout/Sidebar";
import "../styles/globals.css";
import { FollowBar } from "@/components/layout/FollowBar";
import React from "react";
import { LoginModel } from "@/components/models/LoginModel";
import { RegisterModel } from "@/components/models/RegisterModel";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RegisterModel />
        <LoginModel />
        <>
          <div className="h-screen bg-black">
            <div className="container h-full mx-auto xl:px-32 max-w-6xl ">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />
                <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                  {children}
                </div>
                <FollowBar />
              </div>
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
